version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: blog-db-mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql.env
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: blog-php-8.1
    restart: always
    ports:
      - 8089:80
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8111:80
    env_file:
      - ./env/phpmyadmin.env